import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import AuthProvider from './context/AuthProvider'
import { dbConnect } from "@/lib/dbConnect";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const conn = await dbConnect();
  console.log("Connected to database.");
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
          <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
